# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciescategorydata',
            name='CDN_name',
        ),
        migrations.AddField(
            model_name='speciesdata',
            name='categoryName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bddapp.SpeciesCategoryData'),
            preserve_default=False,
        ),
    ]
