# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0002_auto_20170614_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitatdata',
            name='CDN_name',
        ),
        migrations.AddField(
            model_name='speciesdata',
            name='habitatName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bddapp.HabitatData'),
            preserve_default=False,
        ),
    ]
