# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0004_auto_20170614_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitatdata',
            name='detailledHabitatName',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speciescategorydata',
            name='detailledCategoryName',
            field=models.TextField(blank=True),
        ),
    ]
