# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0006_auto_20170614_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeSpeciesCategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largeCategoryName', models.CharField(max_length=100)),
                ('largeDetailledCategoryName', models.TextField(blank=True)),
                ('LargecategoryPictoUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PreciseSpeciesCategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preciseCategoryName', models.CharField(max_length=100)),
                ('preciseDetailledCategoryName', models.TextField(blank=True)),
                ('preciseCategoryPictoUrl', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='speciesdata',
            name='categoryName',
        ),
        migrations.DeleteModel(
            name='SpeciesCategoryData',
        ),
        migrations.AddField(
            model_name='speciesdata',
            name='largeCategoryName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bddapp.LargeSpeciesCategoryData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciesdata',
            name='preciseCategoryName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bddapp.PreciseSpeciesCategoryData'),
            preserve_default=False,
        ),
    ]
