# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0007_auto_20170614_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeCompareData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeCompare', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='largespeciescategorydata',
            old_name='LargecategoryPictoUrl',
            new_name='largeCategoryPictoUrl',
        ),
        migrations.AlterField(
            model_name='speciesdata',
            name='sizeCompare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bddapp.SizeCompareData'),
        ),
    ]
