# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0008_auto_20170614_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesdata',
            name='geographicalSpread',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
