# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0010_relatedspeciesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicesSpeciesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicesSpecies', models.CharField(max_length=100)),
                ('CDN_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bddapp.SpeciesData')),
            ],
        ),
        migrations.AlterField(
            model_name='relatedspeciesdata',
            name='CDN_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Species', to='bddapp.SpeciesData'),
        ),
    ]
