# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0012_auto_20170615_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedspeciesdata',
            name='CDN_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='something', to='bddapp.SpeciesData'),
        ),
    ]
