# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0014_auto_20170615_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdata',
            name='something',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
