# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0017_answerdata_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengedata',
            name='sponsored',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
