# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0018_challengedata_sponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengedata',
            name='geoloc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengedata',
            name='logo',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
