# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0019_auto_20170615_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisespeciescategorydata',
            name='trysomething',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
