# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0020_precisespeciescategorydata_trysomething'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('included_categories', models.ManyToManyField(to='bddapp.YourCategory')),
            ],
        ),
    ]
