# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0021_yourcategory_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='included_categories',
        ),
        migrations.DeleteModel(
            name='YourCategory',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
