# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bddapp', '0022_auto_20170616_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesCategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('detailledCategoryName', models.CharField(max_length=250)),
                ('categoryPictoUrl', models.URLField()),
                ('CDN_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bddapp.SpeciesData')),
            ],
        ),
    ]
